[project]
name = 'BitLynx-DEX'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bitlynx-dex]
path = 'contracts/bitlynx-dex.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
